/* tslint:disable */
/* eslint-disable */
/**
 * 法令APIプロトタイプ
 * <h2>概要</h2> 法令データを取得・検索するための機能をHTTP API方式で提供しています。  <h2>キー要素の解説</h2> 本API（各種エンドポイント）を扱う上で重要な要素について解説します。</br>  * 法令ID（`law_id`）</br> 法令を一意に特定するためのIDです。  * 法令履歴ID（`law_revision_id`）</br> 法令履歴を一意に特定するためのIDです。</br> 法令文書は改正を重ねることで、改版履歴のような版数を持ちます。</br> この版数（法令履歴）を特定するためのIDとなります。  <h2>時点について</h2> 法令APIプロトタイプでは、各法令の過去時点のデータ検索や取得が可能です。</br> 時点指定（`asof`）パラメータを用いることで指定日付時点で有効な法令履歴の特定に役立ちます。  <h2>各エンドポイントの相関性</h2> 各エンドポイントの詳細な説明については、本仕様書で後述されていますのでそちらを参照願います。</br></br> 法令一覧取得API（`/laws`）やキーワード検索API（`/keyword`）を用いて法令を検索し、法令（法令履歴）IDの取得が可能です。</br> その上で法令（法令履歴）単位で以下のようなデータを取得可能です。</br> </br> 法令履歴一覧取得API（`/law_revisions`）：法令履歴（改正履歴）情報を取得</br> 法令本文取得API（`/lawdata`）：法令本文データを取得</br> 添付ファイル取得API（`/attached`）：法令本文に関連する添付ファイルを取得</br></br> ※今回、試験的に法令本文データを別形式（docxなど）にコンバートしたファイルを取得するための法令本文ファイル取得API（`/lawfile`）というエンドポイントを新たに提供しておりますが、こちらも上述のように法令（法令履歴）IDを用いてデータ取得します。</br>  <h2>注意事項</h2> * 本プロトタイプは、一時的な試験提供ですので、実際のシステムへの組み込み等についてはお控えください。実際のサービス提供への活用を頂くには、正式提供している<a href=\"https://elaws.e-gov.go.jp/apitop/\" target=\"_blank\">現行の法令API</a>、もしくは今後検討している高度化後の法令APIをご利用頂く必要があることにご留意ください。  * 使用するデータは、テスト用データのため、一部含まれない法令や、法令標準XMLスキーマには無い属性や項目が含まれていることがあります。  * 本環境はサーバーメンテナンスを行うことがあり、メンテナンス中はご利用がいただけない事があります。また、API仕様についても、テスト期間中に変更される可能性がありますので、ご了承ください。 
 *
 * The version of the OpenAPI document: 2.1.101
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LawsResponseLawsInner } from './LawsResponseLawsInner';
import {
    LawsResponseLawsInnerFromJSON,
    LawsResponseLawsInnerFromJSONTyped,
    LawsResponseLawsInnerToJSON,
} from './LawsResponseLawsInner';

/**
 * 法令一覧取得API レスポンス
 * @export
 * @interface LawsResponse
 */
export interface LawsResponse {
    /**
     * 取得件数の上限（`limit`）、何件目から取得するか（`offset`）適用前のリストに含まれる項目数（検索条件にマッチした全件数）
     * @type {number}
     * @memberof LawsResponse
     */
    totalCount?: number;
    /**
     * 返却するリスト（取得件数の上限（`limit`）、何件目から取得するか（`offset`）適用後）に含まれる項目数
     * @type {number}
     * @memberof LawsResponse
     */
    count: number;
    /**
     * 次の何件目から取得するか（`offset`）。末尾まで取得が完了した場合はnull
     * @type {number}
     * @memberof LawsResponse
     */
    nextOffset?: number | null;
    /**
     * 法令ID単位の法令情報
     * @type {Array<LawsResponseLawsInner>}
     * @memberof LawsResponse
     */
    laws?: Array<LawsResponseLawsInner>;
}

/**
 * Check if a given object implements the LawsResponse interface.
 */
export function instanceOfLawsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;

    return isInstance;
}

export function LawsResponseFromJSON(json: any): LawsResponse {
    return LawsResponseFromJSONTyped(json, false);
}

export function LawsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LawsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalCount': !exists(json, 'total_count') ? undefined : json['total_count'],
        'count': json['count'],
        'nextOffset': !exists(json, 'next_offset') ? undefined : json['next_offset'],
        'laws': !exists(json, 'laws') ? undefined : ((json['laws'] as Array<any>).map(LawsResponseLawsInnerFromJSON)),
    };
}

export function LawsResponseToJSON(value?: LawsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total_count': value.totalCount,
        'count': value.count,
        'next_offset': value.nextOffset,
        'laws': value.laws === undefined ? undefined : ((value.laws as Array<any>).map(LawsResponseLawsInnerToJSON)),
    };
}

